### ISSUE TITLE
No linebreaks in PDF text highlight

### ISSUE THREAD

**Issue by robert-koetsier** [mcanouil/quarto-highlight-text#18]
Thanks for creating this useful extension! I've tried to highlight text but it seems that colored text will not line break in PDF. I'm not experienced with LaTex, but I expect that the issue is that `\\colorbox` which is used for coloring text background does not support line breaks. 

The issue is shown in the pdf, for a reproducible example see the .qmd file: 

[line_breaking.pdf](https://github.com/user-attachments/files/17585310/line_breaking.pdf)
[line_breaking.qmd.txt](https://github.com/user-attachments/files/17585317/line_breaking.qmd.txt)

**Comment by mcanouil** [comment]
Thanks!
This is going to need a bit of work.

For reference: https://tex.stackexchange.com/questions/312574/colorbox-does-not-linebreak

**Comment by mcanouil** [comment]
It should now works with [Highlight Text 1.0.1](https://github.com/mcanouil/quarto-highlight-text/releases/tag/1.0.1)

**Comment by mcanouil** [comment]
@robert-koetsier I had to change the support for line wrapping.
it's no longer the default and needs to be opt-in as it lead to more issues than it solved.
See https://github.com/mcanouil/quarto-highlight-text/tree/1.1.3?tab=readme-ov-file#limitations

**Comment by mcanouil** [comment]
FYI, `lualatex` engine and the `lua-ul` package offers a better support for background highlight.
This is now available in Highlight Text 1.3.0.
See the difference in the rendered examples: https://m.canouil.dev/quarto-highlight-text/
