### ISSUE TITLE
Consider using Obsidian's highlight syntax if possible

### ISSUE THREAD

**Issue by parmsam** [mcanouil/quarto-highlight-text#23]
I recently found out that Obsidian's flavor of Markdown has highlighting using the `==` syntax. Example from their documentation [here](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Bold%2C+italics%2C+highlights).

Is it possible to bring that syntax into Quarto via an extension like this or would that be something for the main Quarto dev team to consider?

**Comment by mcanouil** [comment]
Thanks for the interest, but I don't want to confuse users with several syntaxes and have to maintain that.
Note that this extension does way more than what Obsidian seems to do with its "highlight" syntax.

Markdown syntax is the one from Pandoc.

I expect Quarto CLI maintainers to provide nearly the same answer but feel free to ask them.
